import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
// import SideBar from "@/components/SideBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "REACHA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Navbar />
        {/* <SideBar/> */}
        <main className="relative overflow-hidden flex space-between bg-slate-50"> 
          
          <div>{children}</div>
          
        </main> 
      </body>
    </html>
  );
}
